services:
  frontend:
    build:
      context: ./frontend
      target: deploy
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    volumes:
      - frontend_build:/app

  backend:
    build:
      context: ./backend
      target: release
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  frontend_build:
